import Link from "next/link";

export const metadata = {
  title: "Terms of Service — arfour",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-t-black text-t-text font-mono px-6 py-12">
      <div className="max-w-2xl mx-auto">
        <Link
          href="/"
          className="text-t-green text-xs hover:underline mb-8 inline-block"
        >
          &larr; Back to arfour
        </Link>

        <h1 className="text-xl font-bold text-t-green mb-6 tracking-wider">
          TERMS OF SERVICE
        </h1>
        <p className="text-xs text-t-dim mb-8">Last updated: February 2026</p>

        <div className="space-y-6 text-xs leading-relaxed">
          <section>
            <h2 className="text-sm font-bold text-t-amber mb-2 uppercase tracking-wider">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using arfour (&quot;the Service&quot;), you agree to be bound
              by these Terms of Service. If you do not agree to these terms, do not
              use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-bold text-t-amber mb-2 uppercase tracking-wider">
              2. No Investment Advice
            </h2>
            <p>
              arfour is an informational and educational tool only. The Service does
              not provide investment advice, financial advice, trading advice, or any
              other sort of professional advice. No content on the Service constitutes
              a recommendation to buy, sell, or hold any security, financial product,
              or instrument.
            </p>
            <p className="mt-2">
              You should always conduct your own research and consult with a licensed
              financial advisor before making any investment decisions.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-bold text-t-amber mb-2 uppercase tracking-wider">
              3. AI-Generated Content Disclaimer
            </h2>
            <p>
              All analysis produced by arfour is generated by artificial intelligence
              models. AI-generated content may contain errors, inaccuracies,
              hallucinations, or outdated information. The Service makes no guarantee
              regarding the accuracy, completeness, or timeliness of any analysis.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-bold text-t-amber mb-2 uppercase tracking-wider">
              4. Credits and Payments
            </h2>
            <p>
              The Service operates on a credit-based system. Free-tier users receive a
              limited number of analysis credits that reset weekly. Additional credits
              can be purchased via our payment processor (Stripe).
            </p>
            <p className="mt-2">
              Purchased credits are non-refundable unless an analysis fails due to a
              system error, in which case credits are automatically refunded. Credits
              have no cash value and cannot be transferred.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-bold text-t-amber mb-2 uppercase tracking-wider">
              5. Acceptable Use
            </h2>
            <p>You agree not to:</p>
            <ul className="list-none ml-2 mt-1 space-y-1">
              <li className="before:content-['›_'] before:text-t-green before:mr-1">
                Use the Service for any unlawful purpose
              </li>
              <li className="before:content-['›_'] before:text-t-green before:mr-1">
                Attempt to circumvent rate limits or credit controls
              </li>
              <li className="before:content-['›_'] before:text-t-green before:mr-1">
                Redistribute or resell analysis output commercially without permission
              </li>
              <li className="before:content-['›_'] before:text-t-green before:mr-1">
                Interfere with or disrupt the Service infrastructure
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-sm font-bold text-t-amber mb-2 uppercase tracking-wider">
              6. Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by law, arfour and its operators shall
              not be liable for any indirect, incidental, special, consequential, or
              punitive damages, or any loss of profits or revenues, whether incurred
              directly or indirectly, or any loss of data, use, goodwill, or other
              intangible losses resulting from your use of the Service.
            </p>
            <p className="mt-2">
              In no event shall total liability exceed the amount you paid for the
              Service in the twelve (12) months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-bold text-t-amber mb-2 uppercase tracking-wider">
              7. Account Termination
            </h2>
            <p>
              You may delete your account at any time from within the Service. We
              reserve the right to suspend or terminate accounts that violate these
              terms.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-bold text-t-amber mb-2 uppercase tracking-wider">
              8. Changes to Terms
            </h2>
            <p>
              We may update these terms from time to time. Continued use of the
              Service after changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-bold text-t-amber mb-2 uppercase tracking-wider">
              9. Contact
            </h2>
            <p>
              For questions about these terms, contact us at the email address
              provided in the application.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-6 border-t border-t-border">
          <Link
            href="/privacy"
            className="text-t-amber text-xs hover:underline"
          >
            Privacy Policy &rarr;
          </Link>
        </div>
      </div>
    </div>
  );
}
