import type { AnalysisResult } from "@/lib/types";

/**
 * Truncated real AAPL analysis used on the public landing page.
 * Shows visitors what they get before signing up.
 */
export const SAMPLE_REPORT: AnalysisResult = {
  ticker: "AAPL",
  filepath: "/sample",
  sections: {
    deep_dive: `## Section 0: Executive Summary

### Company Snapshot

| Field                | Data                              |
|----------------------|----------------------------------|
| Company Name         | Apple Inc.                       |
| Ticker               | AAPL                             |
| Sector / Industry    | Technology / Consumer Electronics |
| Market Cap           | $4.05 trillion (Dec 2025)         |
| Current Price        | $264.18 (Feb 27, 2026)            |
| 52-Week Range        | $169.21 - $288.62                  |
| Average Daily Volume | ~37.3 million shares               |
| Dividend Yield       | ~0.39%                            |

---

### 5-Bullet Investment Thesis

- **Apple's integrated ecosystem and premium brand continue to drive durable pricing power and high margin structures; FY25 gross margin of 46.9% and operating margin of 32% reflect strong unit economics.** [High Confidence]

- **Services segment delivers recurring, high-margin revenue (~26% of total), growing steadily despite regulatory scrutiny, underpinning diversification from hardware cyclicality.** [Medium Confidence]

- **Robust capital allocation with $90.7B stock repurchases and sustainable dividends, underpinned by exceptional ROIC (45.9%) and strong free cash flow (~$99B) generation, supports shareholder returns and value creation.** [High Confidence]

- **Valuation premiums reflect market expectations for continued mid-single-digit revenue growth (~6-7% CAGR), margin stability, and successful innovation; downside risks include regulatory and competitive pressures potentially impairing service growth.** [Medium Confidence]

- **Geopolitical, supply chain, and regulatory risks, especially related to China exposure (~17% revenue) and antitrust challenges to App Store monetization, represent material risks demanding ongoing monitoring.** [High Confidence]

---

### Conviction & Risk Summary

| Dimension             | Rating                     |
|-----------------------|----------------------------|
| Conviction (1\u201310)     | 7                          |
| Risk Profile          | Moderate                   |
| Investor Fit          | Growth / Compounder        |
| Time Horizon          | 3\u20135 years                  |
| Position Recommendation| Starter to Full Position  |

---

### One-Sentence Verdict

Apple remains a dominant, high-quality compounder with robust profitability and innovation optionality, but current valuation embeds limited margin of safety given intensifying regulatory and competitive risks.

---

## Section 1: Business Model, Competitive Moat, and Unit Economics

### 1A. Business Model Architecture

- Apple Inc. operates primarily by designing, manufacturing, and marketing consumer electronics, software, and digital services.
- **Revenue streams**:
  - **Product Sales**: iPhone (50.36% of FY25 revenue), Mac, iPad, Wearables/Home/Accessories.
  - **Services**: App Store, Apple Music, iCloud, Apple TV+, and other digital subscription and usage-based services (26.23% of FY25 revenue).
- **Pricing model**: Primarily transactional for hardware (premium fixed pricing) with recurring revenues generated by services through subscriptions and usage fees.

### 1B. Competitive Moat Assessment

| Moat Source                | Strength   | Analysis                                                                 |
|---------------------------|------------|--------------------------------------------------------------------------|
| Intellectual Property      | Strong     | Extensive portfolio across hardware, software, design                    |
| Switching Costs            | Strong     | Ecosystem lock-in with iOS/macOS, data, services, accessories            |
| Network Effects           | Moderate   | App Store developer community creates platform effects                   |
| Brand and Mindshare       | Strong     | Premium brand recognized globally, driving loyalty and premium pricing   |
| Cost Advantages           | Moderate   | Scale benefits and supply chain efficiency                               |

> *This is a preview. The full report contains 14 sections covering financials, valuation, risks, catalysts, and more. [Sign up to run your own analysis.]*`,

    perspectives: `## Eleanor Grant \u2014 Deep Value & Capital Preservation

### Verdict
- **Rating:** Watchlist
- **Confidence:** 7
- **Time Horizon:** 3\u20135 years

### Thesis
- Apple exhibits a **rock-solid balance sheet** with manageable debt ($90.51B) fully supported by exceptional free cash flow (~$99B) and strong interest coverage.
- The company generates **extraordinarily high free cash flow and ROIC (~46%)**, reflective of a durable, scalable business model with fortress-like margins.
- However, the **current valuation (~34x P/E) embeds limited margin of safety**, pricing in near-perfect execution on innovation and regulatory stability.
- **Downside risk is primarily regulatory and competitive**\u2014notably antitrust threats to the App Store monetization.

### Position Sizing Suggestion
- **Small to Moderate** position size initially. Incremental build recommended upon clearer regulatory outcomes or valuation re-rating below ~$240 per share.

---

## Daniel Cho \u2014 Quality Compounder

### Verdict
- **Rating:** Watchlist
- **Confidence:** 7
- **Time Horizon:** 3\u20135 years

### Thesis
- Apple possesses a **robust and durable competitive moat** anchored in its premium brand, integrated ecosystem, substantial switching costs, and wide IP portfolio.
- The **Services segment (~26% of revenue) provides recurring, high-margin revenue** that diversifies beyond cyclical hardware.
- Management executes **disciplined capital allocation** with shareholder-friendly buybacks and sustainable dividends.
- Despite strong fundamentals, **valuation is elevated (~34x P/E)** with limited downside buffer.

### Position Sizing Suggestion
- **Watchlist to Small-Moderate:** Cautious incremental entry (~3\u20135% portfolio weight) while monitoring regulatory and innovation developments.

---

## Victor Alvarez \u2014 Macro-Strategic & Cycle Analyst

### Verdict
- **Rating:** Watchlist
- **Confidence:** 7
- **Time Horizon:** 12\u201318 months

### Thesis
- Apple is a high-quality compounder with a durable moat, but the **macro regime is late-cycle** with moderate headwinds for consumer discretionary spending.
- Current valuation (~34x P/E) embeds optimistic growth assumptions that leave **little buffer against cyclical or regulatory shocks**.
- Near-term catalysts\u2014March 2026 product launch and upcoming regulatory rulings\u2014are key inflection points.

### Position Sizing Suggestion
- **Small to Moderate.** Cautious incremental build advised. Scale up only with clearer regulatory resolution or demonstrable AI/hardware acceleration.`,

    synthesis: `## TriView Synthesis

### Consensus Points
All three analysts concur that Apple is a high-quality compounder with a durable competitive moat anchored in its integrated ecosystem, premium brand, and high-margin Services segment (~26% of revenue). Each highlights Apple's exceptional free cash flow generation (~$99B), strong ROIC (~46%), and disciplined capital allocation. They uniformly recognize that current valuation multiples (~34x P/E) are elevated and embed optimistic assumptions.

### Verdict Summary Table

| Dimension      | Eleanor Grant (Value)              | Daniel Cho (Compounder)              | Victor Alvarez (Macro)             |
|----------------|-----------------------------------|-------------------------------------|------------------------------------|
| Rating         | Watchlist                         | Watchlist                           | Watchlist                          |
| Confidence     | 7                                 | 7                                   | 7                                  |
| Time Horizon   | 3\u20135 years                         | 3\u20135 years                           | 12\u201318 months                       |
| Position Size  | Small to Moderate, incremental   | Watchlist to Small-Moderate (~3\u20135%)  | Small to Moderate, cautious       |

### Where the Market May Be Mispricing
The market may be mispricing the **risk asymmetry around regulatory/legal shocks and innovation payoffs**, underappreciating the probability and financial impact of negative regulatory surprises while modestly discounting possible acceleration from new product cycles and AI.

### Overall Risk-Reward Profile
Apple offers a fundamentally robust business with strong recurring high-margin revenue that supports exceptional capital returns and resilient profitability. However, the premium valuation reflects confidence in sustained growth that may be vulnerable to intensifying regulatory scrutiny and geopolitical risks.

### Key KPIs to Monitor
1. **Regulatory developments** on antitrust investigations\u2014timing, scope, and financial impact on App Store monetization
2. **Services segment revenue growth** and margin trends
3. **AI initiatives and new hardware launches** (foldable iPhone, March 2026 launch)
4. **Macroeconomic indicators** affecting consumer discretionary demand
5. **Valuation trends and buyback activity**`,
  },
  persona_verdicts: [
    {
      persona_id: "eleanor",
      persona_name: "Eleanor Grant",
      persona_label: "Deep Value & Capital Preservation",
      rating: "Watchlist",
      confidence: 0.7,
      time_horizon: "3-5 years",
      position_size: "Small",
      available: true,
    },
    {
      persona_id: "daniel",
      persona_name: "Daniel Cho",
      persona_label: "Quality Compounder",
      rating: "Watchlist",
      confidence: 0.7,
      time_horizon: "3-5 years",
      position_size: "Small",
      available: true,
    },
    {
      persona_id: "victor",
      persona_name: "Victor Alvarez",
      persona_label: "Macro-Strategic & Cycle Analyst",
      rating: "Watchlist",
      confidence: 0.7,
      time_horizon: "12-18 months",
      position_size: "Small",
      available: true,
    },
  ],
};
