import type { AnalysisResult } from "@/lib/types";

/**
 * Truncated real AAPL analysis used on the public landing page.
 * Shows visitors what they get before signing up.
 */
export const SAMPLE_REPORT: AnalysisResult = {
  ticker: "AAPL",
  filepath: "/sample",
  sections: {
    deep_dive: `## Section 0: Executive Summary

### Company Snapshot

| Field                | Data                              |
|----------------------|----------------------------------|
| Company Name         | Apple Inc.                       |
| Ticker               | AAPL                             |
| Sector / Industry    | Technology / Consumer Electronics |
| Market Cap           | $4.05 trillion (Dec 2025)         |
| Current Price        | $264.18 (Feb 27, 2026)            |
| 52-Week Range        | $169.21 - $288.62                  |
| Average Daily Volume | ~37.3 million shares               |
| Dividend Yield       | ~0.39%                            |

---

### 5-Bullet Investment Thesis

- **Apple's integrated ecosystem and premium brand continue to drive durable pricing power and high margin structures; FY25 gross margin of 46.9% and operating margin of 32% reflect strong unit economics.** [High Confidence]

- **Services segment delivers recurring, high-margin revenue (~26% of total), growing steadily despite regulatory scrutiny, underpinning diversification from hardware cyclicality.** [Medium Confidence]

- **Robust capital allocation with $90.7B stock repurchases and sustainable dividends, underpinned by exceptional ROIC (45.9%) and strong free cash flow (~$99B) generation, supports shareholder returns and value creation.** [High Confidence]

- **Valuation premiums reflect market expectations for continued mid-single-digit revenue growth (~6-7% CAGR), margin stability, and successful innovation; downside risks include regulatory and competitive pressures potentially impairing service growth.** [Medium Confidence]

- **Geopolitical, supply chain, and regulatory risks, especially related to China exposure (~17% revenue) and antitrust challenges to App Store monetization, represent material risks demanding ongoing monitoring.** [High Confidence]

---

### Conviction & Risk Summary

| Dimension             | Rating                     |
|-----------------------|----------------------------|
| Conviction (1\u201310)     | 7                          |
| Risk Profile          | Moderate                   |
| Investor Fit          | Growth / Compounder        |
| Time Horizon          | 3\u20135 years                  |
| Position Recommendation| Starter to Full Position  |

---

### One-Sentence Verdict

Apple remains a dominant, high-quality compounder with robust profitability and innovation optionality, but current valuation embeds limited margin of safety given intensifying regulatory and competitive risks.

---

## Section 1: Business Model, Competitive Moat, and Unit Economics

### 1A. Business Model Architecture

- Apple Inc. operates primarily by designing, manufacturing, and marketing consumer electronics, software, and digital services.
- **Revenue streams**:
  - **Product Sales**: iPhone (50.36% of FY25 revenue), Mac, iPad, Wearables/Home/Accessories.
  - **Services**: App Store, Apple Music, iCloud, Apple TV+, and other digital subscription and usage-based services (26.23% of FY25 revenue).
- **Pricing model**: Primarily transactional for hardware (premium fixed pricing) with recurring revenues generated by services through subscriptions and usage fees.

### 1B. Competitive Moat Assessment

| Moat Source                | Strength   | Analysis                                                                 |
|---------------------------|------------|--------------------------------------------------------------------------|
| Intellectual Property      | Strong     | Extensive portfolio across hardware, software, design                    |
| Switching Costs            | Strong     | Ecosystem lock-in with iOS/macOS, data, services, accessories            |
| Network Effects           | Moderate   | App Store developer community creates platform effects                   |
| Brand and Mindshare       | Strong     | Premium brand recognized globally, driving loyalty and premium pricing   |
| Cost Advantages           | Moderate   | Scale benefits and supply chain efficiency                               |

> *This is a preview. The full report contains 14 sections covering financials, valuation, risks, catalysts, and more. [Sign up to run your own analysis.]*`,

    perspectives: `## Eleanor Grant — Deep Value & Capital Preservation

### Verdict
- **Rating:** Avoid
- **Confidence:** 8
- **Time Horizon:** 3–5 years

### Thesis
- Apple's balance sheet is solid with manageable debt ($90.51B) and exceptional free cash flow (~$99B), but **that quality is already priced in — and then some.**
- At ~34x P/E, you're paying a premium that embeds near-perfect execution. **The margin of safety is essentially zero.** In my framework, that's a disqualifying condition regardless of business quality.
- **Downside risk is real and underappreciated**: antitrust threats to App Store monetization could impair the highest-margin segment, and the market isn't pricing that in.
- I'd need to see a 25–30% pullback before this becomes interesting from a value perspective. Great business, terrible price.

### Position Sizing Suggestion
- **None.** I won't pay 34x earnings for a company growing revenue at mid-single digits. Wake me up at $200.

---

## Daniel Cho — Quality Compounder

### Verdict
- **Rating:** Buy
- **Confidence:** 8
- **Time Horizon:** 3–5 years

### Thesis
- Apple possesses a **best-in-class competitive moat** — integrated ecosystem, massive switching costs, and a Services segment (~26% of revenue) that's building a recurring revenue fortress.
- **ROIC of ~46% is extraordinary** and sustainable. Management's capital allocation is textbook: $90.7B in buybacks funded by organic cash flow, not leverage. This is compounding in its purest form.
- The valuation premium (~34x P/E) is justified by the durability and predictability of these returns. **Quality deserves a premium, and Apple is the quality benchmark.**
- Regulatory risk is real but manageable — Apple has navigated these waters before and has multiple levers to adapt.

### Position Sizing Suggestion
- **Moderate** — 4–6% portfolio weight. This is a core holding you compound into over time, not a trade.

---

## Victor Alvarez — Macro-Strategic & Cycle Analyst

### Verdict
- **Rating:** Watchlist
- **Confidence:** 5
- **Time Horizon:** 6–12 months

### Thesis
- The macro picture is messy right now. We're **late-cycle with consumer discretionary facing headwinds** from sticky inflation and elevated rates. Apple isn't immune to this.
- Positioning is extremely crowded — Apple is the largest weight in every index fund and the most widely held stock on the planet. **When the cycle turns, the crowding unwinds violently.**
- That said, a Fed pivot to easing would be a massive tailwind for duration assets like Apple. I'm not willing to bet against that possibility, which is why this isn't an Avoid.
- **I'm waiting for the next ISM print and Fed guidance before committing.** The setup could flip to Buy quickly if the macro regime shifts.

### Position Sizing Suggestion
- **Small** at most. I'd keep powder dry and wait for a clearer macro signal. If the Fed pivots dovish, I'm buying aggressively.`,

    synthesis: `## TriView Synthesis\n\n### Consensus Points\nAll three analysts agree Apple is a high-quality business with a durable competitive moat, exceptional free cash flow (~$99B), and strong ROIC (~46%). They also agree that Services (~26% of revenue) is the most strategically important growth vector. However, **this is where consensus ends \u2014 and the divergence is the most valuable signal in this report.**\n\nThe unanimous recognition of quality may itself be a warning sign: when three independent frameworks all see the same strengths, those strengths are likely already priced in. The real question is whether the current ~34x P/E adequately compensates for the risks \u2014 and here the panel splits sharply.\n\n### Points of Disagreement\nThe core tension is between **business quality** and **price discipline**. Eleanor Grant sees a company priced for perfection with zero margin of safety \u2014 her framework simply will not allow a Buy at these multiples regardless of quality. Daniel Cho argues the premium is justified precisely because this level of quality and compounding power is rare. Victor Alvarez sidesteps the valuation debate entirely, focusing on macro timing: even if Apple is fairly valued, the cycle position and crowded positioning create near-term risk.\n\nThis is not a case of one analyst being right and others wrong. **Their frameworks are asking different questions**: Eleanor asks \u201cWhat could go wrong?\u201d, Daniel asks \u201cCan this compound for a decade?\u201d, and Victor asks \u201cWhat does the macro regime mean for this name in the next 12 months?\u201d\n\n### Verdict Summary Table\n\n| Dimension      | Eleanor Grant (Value)     | Daniel Cho (Compounder)   | Victor Alvarez (Macro)    |\n|----------------|--------------------------|--------------------------|--------------------------|\n| Rating         | Avoid                    | Buy                      | Watchlist                |\n| Confidence     | 8                        | 8                        | 5                        |\n| Time Horizon   | 3\u20135 years               | 3\u20135 years               | 6\u201312 months              |\n| Position Size  | None                     | Moderate (4\u20136%)          | Small                    |\n\n### Where the Market May Be Mispricing\nThe sharpest tension \u2014 Eleanor at Avoid vs. Daniel at Buy \u2014 suggests the market may be **mispricing the probability of regulatory damage to App Store monetization**. Daniel\u2019s framework absorbs this as manageable; Eleanor\u2019s framework treats it as a potential margin-of-safety destroyer at current multiples. If antitrust enforcement materially impairs Services margins, the stock is overvalued. If Apple navigates it cleanly, the compounder thesis holds.\n\n### Overall Risk-Reward Profile\nApple is a fundamentally exceptional business where the investment debate is entirely about price and timing, not quality. The Avoid-vs-Buy split on this panel is itself the most informative signal: **great company, genuinely debatable entry point.** Investors with long time horizons and tolerance for near-term drawdowns may side with Cho; those demanding margin of safety will wait with Grant.\n\n### Key KPIs to Monitor\n1. **Antitrust rulings and App Store regulatory impact** \u2014 the single biggest swing factor across all three frameworks\n2. **Services segment margin trends** \u2014 canary in the coal mine for regulatory damage\n3. **Fed policy direction and rate trajectory** \u2014 Alvarez\u2019s primary trigger for upgrading or downgrading\n4. **Consumer discretionary spending indicators** \u2014 ISM, retail sales, consumer confidence\n5. **Buyback pace and valuation multiples** \u2014 if Apple accelerates buybacks on weakness, Grant\u2019s entry point approaches`,
  },
  persona_verdicts: [
    {
      persona_id: "eleanor",
      persona_name: "Eleanor Grant",
      persona_label: "Deep Value & Capital Preservation",
      rating: "Avoid",
      confidence: 8,
      time_horizon: "3-5 years",
      position_size: "None",
      available: true,
    },
    {
      persona_id: "daniel",
      persona_name: "Daniel Cho",
      persona_label: "Quality Compounder",
      rating: "Buy",
      confidence: 8,
      time_horizon: "3-5 years",
      position_size: "Moderate",
      available: true,
    },
    {
      persona_id: "victor",
      persona_name: "Victor Alvarez",
      persona_label: "Macro-Strategic & Cycle Analyst",
      rating: "Watchlist",
      confidence: 5,
      time_horizon: "6-12 months",
      position_size: "Small",
      available: true,
    },
  ],
};
